/*
 Generated by org.infinispan.protostream.annotations.impl.processor.MarshallerSourceCodeGenerator
 for class at.tfr.securefs.cache.ClusterState
*/

package at.tfr.securefs.cache;

/**
 * WARNING: Generated code! Do not edit!
 *
 * @private
 */
@javax.annotation.processing.Generated(
   value = "org.infinispan.protostream.annotations.impl.processor.AutoProtoSchemaBuilderAnnotationProcessor",
   comments = "Please do not edit this file!"
)
@SuppressWarnings("all")
public final class ClusterState$___Marshaller_5407b2543df093e43ca08a173676e42a24c3c0e7a2a6ff4590e187da4a5ff415 extends org.infinispan.protostream.annotations.impl.GeneratedMarshallerBase implements org.infinispan.protostream.ProtobufTagMarshaller<ClusterState> {

   private org.infinispan.protostream.impl.BaseMarshallerDelegate __md$1;
   
   @Override
   public Class<ClusterState> getJavaClass() { return ClusterState.class; }
   
   @Override
   public String getTypeName() { return "ClusterState"; }
   
   @Override
   public ClusterState read(ReadContext $1) throws java.io.IOException {
      final org.infinispan.protostream.TagReader $in = $1.getReader();
      final ClusterState o = new ClusterState();
      long __bits$0 = 0;
      java.util.ArrayList __c$1 = null;
      boolean done = false;
      while (!done) {
         final int tag = $in.readTag();
         switch (tag) {
            case 0: {
               done = true;
               break;
            }
            case (1 << org.infinispan.protostream.descriptors.WireType.TAG_TYPE_NUM_BITS | org.infinispan.protostream.descriptors.WireType.WIRETYPE_LENGTH_DELIMITED): {
               if (__md$1 == null) __md$1 = ((org.infinispan.protostream.impl.SerializationContextImpl) $1.getSerializationContext()).getMarshallerDelegate(at.tfr.securefs.cache.StateInfo.class);
               int length = $in.readUInt32();
               int oldLimit = $in.pushLimit(length);
               at.tfr.securefs.cache.StateInfo __v$1 = (at.tfr.securefs.cache.StateInfo) readMessage(__md$1, $1);
               $in.checkLastTagWas(0);
               $in.popLimit(oldLimit);
               if (__c$1 == null) __c$1 = new java.util.ArrayList();
               __c$1.add(__v$1);
               break;
            }
            case (2 << org.infinispan.protostream.descriptors.WireType.TAG_TYPE_NUM_BITS | org.infinispan.protostream.descriptors.WireType.WIRETYPE_LENGTH_DELIMITED): {
               String __v$2 = $in.readString();
               o.node = __v$2;
               break;
            }
            case (3 << org.infinispan.protostream.descriptors.WireType.TAG_TYPE_NUM_BITS | org.infinispan.protostream.descriptors.WireType.WIRETYPE_LENGTH_DELIMITED): {
               String __v$3 = $in.readString();
               o.clusterKey = __v$3;
               break;
            }
            case (4 << org.infinispan.protostream.descriptors.WireType.TAG_TYPE_NUM_BITS | org.infinispan.protostream.descriptors.WireType.WIRETYPE_VARINT): {
               boolean __v$4 = $in.readBool();
               o.hasSecret = __v$4;
               __bits$0 |= 1L;
               break;
            }
            case (5 << org.infinispan.protostream.descriptors.WireType.TAG_TYPE_NUM_BITS | org.infinispan.protostream.descriptors.WireType.WIRETYPE_VARINT): {
               int __v$5 = $in.readInt32();
               o.secretHash = __v$5;
               __bits$0 |= 2L;
               break;
            }
            default: {
               if (!$in.skipField(tag)) done = true;
            }
         }
      }
      if (__c$1 != null) {
         o.stateInfo = (at.tfr.securefs.cache.StateInfo[])__c$1.toArray(new at.tfr.securefs.cache.StateInfo[0]);
      } else {
         o.stateInfo = new at.tfr.securefs.cache.StateInfo[0];
      }
      
      if ((__bits$0 & 3L) != 3L) {
         final StringBuilder missing = new StringBuilder();
         if ((__bits$0 & 1L) == 0) {
            missing.append("hasSecret");
         }
         if ((__bits$0 & 2L) == 0) {
            if (missing.length() > 0) missing.append(", ");
            missing.append("secretHash");
         }
         throw new java.io.IOException("Required field(s) missing from input stream : " + missing);
      }
      return o;
   }
   
   @Override
   public void write(WriteContext $1, ClusterState $2) throws java.io.IOException {
      final org.infinispan.protostream.TagWriter $out = $1.getWriter();
      final ClusterState o = (ClusterState) $2;
      {
         final at.tfr.securefs.cache.StateInfo[] __a$1 = (at.tfr.securefs.cache.StateInfo[]) o.stateInfo;
         if (__a$1 != null) 
            for (int i = 0; i < __a$1.length; i++) {
               final at.tfr.securefs.cache.StateInfo __v$1 = __a$1[i];
               {
                  if (__md$1 == null) __md$1 = ((org.infinispan.protostream.impl.SerializationContextImpl) $1.getSerializationContext()).getMarshallerDelegate(at.tfr.securefs.cache.StateInfo.class);
                  writeNestedMessage(__md$1, $1, 1, __v$1);
               }
            }
      }
      {
         final String __v$2 = o.node;
         if (__v$2 != null) $out.writeString(2, __v$2);
      }
      {
         final String __v$3 = o.clusterKey;
         if (__v$3 != null) $out.writeString(3, __v$3);
      }
      {
         final boolean __v$4 = o.hasSecret;
         $out.writeBool(4, __v$4);
      }
      {
         final int __v$5 = o.secretHash;
         $out.writeInt32(5, __v$5);
      }
   }
}
