
package at.tfr.securefs.client.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "FileServiceBean", targetNamespace = "http://securefs.tfr.at/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileServiceBean {


    /**
     *
     * @param relativePath
     * @return
     *     returns byte[]
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "bytes", targetNamespace = "")
    @RequestWrapper(localName = "read", targetNamespace = "http://securefs.tfr.at/", className = "at.tfr.securefs.client.ws.Read")
    @ResponseWrapper(localName = "readResponse", targetNamespace = "http://securefs.tfr.at/", className = "at.tfr.securefs.client.ws.ReadResponse")
    public byte[] read(
        @WebParam(name = "relativePath", targetNamespace = "")
        String relativePath)
        throws IOException_Exception
    ;

    /**
     *
     * @param relativePath
     * @param bytes
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "write", targetNamespace = "http://securefs.tfr.at/", className = "at.tfr.securefs.client.ws.Write")
    @ResponseWrapper(localName = "writeResponse", targetNamespace = "http://securefs.tfr.at/", className = "at.tfr.securefs.client.ws.WriteResponse")
    public void write(
        @WebParam(name = "relativePath", targetNamespace = "")
        String relativePath,
        @WebParam(name = "bytes", targetNamespace = "")
        byte[] bytes)
        throws IOException_Exception
    ;

}
