/*
 Generated by org.infinispan.protostream.annotations.impl.processor.AutoProtoSchemaBuilderAnnotationProcessor
 for class at.tfr.securefs.cache.InfinispanSerializationContextInitializer
 annotated with @org.infinispan.protostream.annotations.AutoProtoSchemaBuilder(dependsOn={}, marshallersOnly=false, service=true, autoImportClasses=true, excludeClasses={}, includeClasses={at.tfr.securefs.cache.ClusterState.class, at.tfr.securefs.data.ValidationData.class}, basePackages={}, value={}, schemaPackageName="", schemaFilePath="", schemaFileName="", className="")
 */

package at.tfr.securefs.cache.protostream;

import at.tfr.securefs.cache.ClusterState$___Marshaller_5407b2543df093e43ca08a173676e42a24c3c0e7a2a6ff4590e187da4a5ff415;
import at.tfr.securefs.cache.StateInfo$___Marshaller_86c7f0c94d5cfbeddaf3f0741b4ba640c77a6eea04accec8254fbe929833bb1b;
import at.tfr.securefs.data.ValidationData$___Marshaller_71fa07ac9ff6dd64541a57d8b4963f07ebed14099879cff2a4c31a8a6806349f;
import at.tfr.securefs.key.UiShare$___Marshaller_93258254b8161fd518c8465d83e0e5cd326214aed3cc18837322ff2aa855e308;

/**
 * WARNING: Generated code! Do not edit!
 */
//@javax.annotation.processing.Generated(
//   value = "org.infinispan.protostream.annotations.impl.processor.AutoProtoSchemaBuilderAnnotationProcessor",
//   comments = "Please do not edit this file!"
//)
//@org.infinispan.protostream.annotations.impl.processor.OriginatingClasses({
//   at.tfr.securefs.cache.ClusterState.class,
//   at.tfr.securefs.data.ValidationData.class
//})
/*@org.infinispan.protostream.annotations.AutoProtoSchemaBuilder(
   className = "InfinispanSerializationContextInitializerImpl",
   schemaFileName = "InfinispanSerializationContextInitializer.proto",
   schemaFilePath = "",
   service = true,
   marshallersOnly = false,
   autoImportClasses = true,
   includeClasses = {
      at.tfr.securefs.cache.ClusterState.class,
      at.tfr.securefs.data.ValidationData.class
   }
)*/
@SuppressWarnings("all")
public class InfinispanSerializationContextInitializerImpl implements at.tfr.securefs.cache.InfinispanSerializationContextInitializer, org.infinispan.protostream.GeneratedSchema {

   private static final String PROTO_SCHEMA = "// File name: InfinispanSerializationContextInitializer.proto\n" +
   "// Generated from : at.tfr.securefs.cache.InfinispanSerializationContextInitializer\n" +
   "\n" +
   "syntax = \"proto2\";\n" +
   "\n" +
   "\n" +
   "\n" +
   "/**\n" +
   " * @SuppressWarnings({\"serial\"})\n" +
   " */\n" +
   "message ClusterState {\n" +
   "   \n" +
   "   repeated StateInfo stateInfo = 1;\n" +
   "   \n" +
   "   optional string node = 2;\n" +
   "   \n" +
   "   optional string clusterKey = 3;\n" +
   "   \n" +
   "   required bool hasSecret = 4;\n" +
   "   \n" +
   "   required int32 secretHash = 5;\n" +
   "}\n" +
   "\n" +
   "\n" +
   "/**\n" +
   " * @SuppressWarnings({\"serial\"})\n" +
   " * @XmlRootElement\n" +
   " */\n" +
   "message ValidationData {\n" +
   "   \n" +
   "   optional string modulus = 1;\n" +
   "   \n" +
   "   required int32 threshold = 2;\n" +
   "   \n" +
   "   required int32 nrOfShares = 3;\n" +
   "   \n" +
   "   repeated UiShare uiShares = 4;\n" +
   "}\n" +
   "\n" +
   "\n" +
   "message StateInfo {\n" +
   "   \n" +
   "   optional string host = 1;\n" +
   "   \n" +
   "   optional string info = 2;\n" +
   "}\n" +
   "\n" +
   "\n" +
   "message UiShare {\n" +
   "   \n" +
   "   required int32 index = 1;\n" +
   "   \n" +
   "   optional string share = 2;\n" +
   "   \n" +
   "   optional string realShare = 3;\n" +
   "}\n" +
   "";
   
   @Override
   public String getProtoFileName() { return "InfinispanSerializationContextInitializer.proto"; }
   
   @Override
   public String getProtoFile() { return PROTO_SCHEMA; }
   
   @Override
   public void registerSchema(org.infinispan.protostream.SerializationContext serCtx) {
      serCtx.registerProtoFiles(org.infinispan.protostream.FileDescriptorSource.fromString(getProtoFileName(), getProtoFile()));
   }
   
   @Override
   public void registerMarshallers(org.infinispan.protostream.SerializationContext serCtx) {
      serCtx.registerMarshaller(new ClusterState$___Marshaller_5407b2543df093e43ca08a173676e42a24c3c0e7a2a6ff4590e187da4a5ff415());
      serCtx.registerMarshaller(new ValidationData$___Marshaller_71fa07ac9ff6dd64541a57d8b4963f07ebed14099879cff2a4c31a8a6806349f());
      serCtx.registerMarshaller(new StateInfo$___Marshaller_86c7f0c94d5cfbeddaf3f0741b4ba640c77a6eea04accec8254fbe929833bb1b());
      serCtx.registerMarshaller(new UiShare$___Marshaller_93258254b8161fd518c8465d83e0e5cd326214aed3cc18837322ff2aa855e308());
   }
}
