/*
 Generated by org.infinispan.protostream.annotations.impl.processor.MarshallerSourceCodeGenerator
 for class at.tfr.securefs.data.ValidationData
*/

package at.tfr.securefs.data;

/**
 * WARNING: Generated code! Do not edit!
 *
 * @private
 */
@javax.annotation.processing.Generated(
   value = "org.infinispan.protostream.annotations.impl.processor.AutoProtoSchemaBuilderAnnotationProcessor",
   comments = "Please do not edit this file!"
)
@SuppressWarnings("all")
public final class ValidationData$___Marshaller_71fa07ac9ff6dd64541a57d8b4963f07ebed14099879cff2a4c31a8a6806349f extends org.infinispan.protostream.annotations.impl.GeneratedMarshallerBase implements org.infinispan.protostream.ProtobufTagMarshaller<ValidationData> {

   private org.infinispan.protostream.impl.BaseMarshallerDelegate __md$4;
   
   @Override
   public Class<ValidationData> getJavaClass() { return ValidationData.class; }
   
   @Override
   public String getTypeName() { return "ValidationData"; }
   
   @Override
   public ValidationData read(ReadContext $1) throws java.io.IOException {
      final org.infinispan.protostream.TagReader $in = $1.getReader();
      final ValidationData o = new ValidationData();
      long __bits$0 = 0;
      java.util.ArrayList __c$4 = new java.util.ArrayList();
      boolean done = false;
      while (!done) {
         final int tag = $in.readTag();
         switch (tag) {
            case 0: {
               done = true;
               break;
            }
            case (1 << org.infinispan.protostream.descriptors.WireType.TAG_TYPE_NUM_BITS | org.infinispan.protostream.descriptors.WireType.WIRETYPE_LENGTH_DELIMITED): {
               String __v$1 = $in.readString();
               o.modulus = __v$1;
               break;
            }
            case (2 << org.infinispan.protostream.descriptors.WireType.TAG_TYPE_NUM_BITS | org.infinispan.protostream.descriptors.WireType.WIRETYPE_VARINT): {
               int __v$2 = $in.readInt32();
               o.threshold = __v$2;
               __bits$0 |= 1L;
               break;
            }
            case (3 << org.infinispan.protostream.descriptors.WireType.TAG_TYPE_NUM_BITS | org.infinispan.protostream.descriptors.WireType.WIRETYPE_VARINT): {
               int __v$3 = $in.readInt32();
               o.nrOfShares = __v$3;
               __bits$0 |= 2L;
               break;
            }
            case (4 << org.infinispan.protostream.descriptors.WireType.TAG_TYPE_NUM_BITS | org.infinispan.protostream.descriptors.WireType.WIRETYPE_LENGTH_DELIMITED): {
               if (__md$4 == null) __md$4 = ((org.infinispan.protostream.impl.SerializationContextImpl) $1.getSerializationContext()).getMarshallerDelegate(at.tfr.securefs.key.UiShare.class);
               int length = $in.readUInt32();
               int oldLimit = $in.pushLimit(length);
               at.tfr.securefs.key.UiShare __v$4 = (at.tfr.securefs.key.UiShare) readMessage(__md$4, $1);
               $in.checkLastTagWas(0);
               $in.popLimit(oldLimit);
               __c$4.add(__v$4);
               break;
            }
            default: {
               if (!$in.skipField(tag)) done = true;
            }
         }
      }
      o.uiShares = __c$4;
      
      if ((__bits$0 & 3L) != 3L) {
         final StringBuilder missing = new StringBuilder();
         if ((__bits$0 & 1L) == 0) {
            missing.append("threshold");
         }
         if ((__bits$0 & 2L) == 0) {
            if (missing.length() > 0) missing.append(", ");
            missing.append("nrOfShares");
         }
         throw new java.io.IOException("Required field(s) missing from input stream : " + missing);
      }
      return o;
   }
   
   @Override
   public void write(WriteContext $1, ValidationData $2) throws java.io.IOException {
      final org.infinispan.protostream.TagWriter $out = $1.getWriter();
      final ValidationData o = (ValidationData) $2;
      {
         final String __v$1 = o.modulus;
         if (__v$1 != null) $out.writeString(1, __v$1);
      }
      {
         final int __v$2 = o.threshold;
         $out.writeInt32(2, __v$2);
      }
      {
         final int __v$3 = o.nrOfShares;
         $out.writeInt32(3, __v$3);
      }
      {
         final java.util.Collection __c$4 = o.uiShares;
         if (__c$4 != null) 
            for (java.util.Iterator it = __c$4.iterator(); it.hasNext(); ) {
               final at.tfr.securefs.key.UiShare __v$4 = (at.tfr.securefs.key.UiShare) it.next();
               {
                  if (__md$4 == null) __md$4 = ((org.infinispan.protostream.impl.SerializationContextImpl) $1.getSerializationContext()).getMarshallerDelegate(at.tfr.securefs.key.UiShare.class);
                  writeNestedMessage(__md$4, $1, 4, __v$4);
               }
            }
      }
   }
}
